// Code generated by mfd-generator v0.6.0; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type EventSearch struct {
	search

	ID           *int
	UserTgID     *int64
	Message      *string
	SendAt       *time.Time
	CreatedAt    *time.Time
	StatusID     *int
	IDs          []int
	MessageILike *string
}

func (es *EventSearch) Apply(query *orm.Query) *orm.Query {
	if es == nil {
		return query
	}
	if es.ID != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.ID, es.ID)
	}
	if es.UserTgID != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.UserTgID, es.UserTgID)
	}
	if es.Message != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.Message, es.Message)
	}
	if es.SendAt != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.SendAt, es.SendAt)
	}
	if es.CreatedAt != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.CreatedAt, es.CreatedAt)
	}
	if es.StatusID != nil {
		es.where(query, Tables.Event.Alias, Columns.Event.StatusID, es.StatusID)
	}
	if len(es.IDs) > 0 {
		Filter{Columns.Event.ID, es.IDs, SearchTypeArray, false}.Apply(query)
	}
	if es.MessageILike != nil {
		Filter{Columns.Event.Message, *es.MessageILike, SearchTypeILike, false}.Apply(query)
	}

	es.apply(query)

	return query
}

func (es *EventSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if es == nil {
			return query, nil
		}
		return es.Apply(query), nil
	}
}
